$(document).ready(function() {
	var el = document.getElementById("top-bar");
	console.log(
		'test'
	);
	if(el) {
		el.innerHTML='<div class="core-site-styles"><nav class="navbar navbar-expand-lg bg-white fixed-top"><div class="d-flex w-25 order-0"><a class="navbar-brand mr-1 navbar-vfx" href="#"><img src="css/static/svg/logo.svg?214"><span>motionVFX</span></a></div><div class="navbar-collapse justify-content-center order-2 collapsed-nav" id="collapsingNavbar"><ul class="navbar-nav text-nowrap"><li class="nav-item dropdown"><a class="cursor-pointer nav-link dropdown-toggle product-types-link " data-redirect-link="/store,templates,1.html" id="navbarDropdown" role="button" data-toggle="dropdown">Templates</a><div class="arrow-navbar"></div><div class="dropdown-menu fade" aria-labelledby="navbarDropdown"></div></li><li class="nav-item dropdown"><a class="cursor-pointer nav-link dropdown-toggle product-types-link " data-redirect-link="/store,plugins,2.html" id="navbarDropdown" role="button" data-toggle="dropdown">Plugins</a><div class="arrow-navbar"></div><div class="dropdown-menu fade" aria-labelledby="navbarDropdown"></div></li><li class="nav-item dropdown"><a class="nav-link " href="#" role="button">Compositing elements</a></li><li class="nav-item"><a class="nav-link" href="#">Help</a></li><li class="nav-item dropdown d-lg-none"><a class="nav-link" href="#">Account</a><div class="arrow-navbar"></div><div class="dropdown-menu fade"></div></li></ul></div><div class="navbar-right w-25 text-right order-1 order-lg-last"><button class="menu-icon-svg navbar-toggler"><div class="icon"></div></button><a data-global-search-toggle="" class="search-icon-svg cursor-pointer" id="globalSearchToggle"><div class="icon"></div></a><div class="dropdown d-none d-lg-inline navbar-nav account-dropdown"><a data-auth-section-toggle="" id="authSectionBtn" role="button" class="cursor-pointer head-icon-svg d-none d-md-inline"><div class="icon"></div></a><div class="dropdown-menu fade text-center" aria-labelledby="accountDropdown"></div></div><a role="button" class="bag-icon-svg cursor-pointer d-flex float-right" data-minicart-toggle=""><div class="icon d-inline-flex"></div><small id="cartProductCount" class="d-inline-flex"></small></a></div></nav></div>';
	}
});
